### ISSUE TITLE
Python 3.13 support need

### ISSUE THREAD

**Issue by patrizok** [couchbase/couchbase-python-client#58]
Python 3.13 support need

**Comment by thejcfactor** [comment]
Hi @patrizok  -- Please see the tracking for Python 3.13 support in our JIRA system:  [PYCBC-1613](https://jira.issues.couchbase.com/browse/PYCBC-1613)

We will address Python 3.13 support more quickly than we did Python 3.12, but some changes in Python's C-API mean we need to tweak our C/C++ bindings and that causes a bit of delay for adding new wheels (small team, sprint planning, etc. 😅).  I have made a note to circle back around and update this issue once we have added 3.13 support.

**Comment by thejcfactor** [comment]
Hi @patrizok  -- [PYCBC-1613](https://jira.issues.couchbase.com/browse/PYCBC-1613) has been resolved and [v4.3.4](https://pypi.org/project/couchbase/) has been released which includes Python 3.13 support.
